py36:
  image: python:3.6
  script:
    - apt-get update -q -y
    - pip install -r requirements.txt
    - pip install codecov
    - coverage run --omit=krangpower/method_get.py ./tests.py
    - codecov