test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - apt-get install -y python3-pip
  - pip install -r requirements.txt
  - pip install codecov
  - coverage run --omit=krangpower/method_get.py ./tests.py
  - codecov