sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run --omit=krangpower/method_get.py ./tests.py

after_success:
  - codecov