sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run ./test/eu_lv_fulltest.py
  - coverage run ./test/usage_1/us1.py

after_success:
  - codecov